/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Aura } from './types';

export const AURAS: Aura[] = [
  {
    id: 'common',
    name: 'Common Star',
    chance: 2,
    color: 'from-gray-400 to-gray-200 text-gray-300',
    glowColor: '#9ca3af',
    negativeColor: '#6b7280',
    invertedName: 'Inverted Common',
    description: 'A modest glowing speck orbiting around you.',
    soundFreq: 261.63, // C4
  },
  {
    id: 'uncommon',
    name: 'Uncommon Star',
    chance: 5,
    color: 'from-green-500 to-emerald-300 text-green-400',
    glowColor: '#10b981',
    negativeColor: '#ef4444',
    invertedName: 'Flaring Green Spark',
    description: 'An emerald-glowing trace carrying mild status energy.',
    soundFreq: 293.66, // D4
  },
  {
    id: 'shiny',
    name: 'Shiny Orb',
    chance: 15,
    color: 'from-cyan-400 to-blue-300 text-cyan-300',
    glowColor: '#06b6d4',
    negativeColor: '#f97316',
    invertedName: 'Dull Sub-Aura',
    description: 'A high-vibrational sphere of glowing teal vapor.',
    soundFreq: 329.63, // E4
  },
  {
    id: 'speedster',
    name: 'Speedster Spark',
    chance: 50,
    color: 'from-yellow-400 to-amber-300 text-yellow-300 animate-pulse',
    glowColor: '#eab308',
    negativeColor: '#a855f7',
    invertedName: 'Decelerator Trail',
    description: 'Emits electric yellow static arcs. Boosts spirit frequency.',
    soundFreq: 349.23, // F4
  },
  {
    id: 'ember_flare',
    name: 'Ember Flare🔥',
    chance: 60,
    color: 'from-amber-600 via-orange-500 to-red-500 text-orange-400 animate-pulse font-bold',
    glowColor: '#f97316',
    negativeColor: '#0ea5e9',
    invertedName: 'Cold Spark',
    description: 'A burning cinder of plasma that sparks at high velocity.',
    soundFreq: 350.00,
    relatedBiome: 'FIRE',
  },
  {
    id: 'gentle_zephyr',
    name: 'Gentle Zephyr wind💨',
    chance: 80,
    color: 'from-teal-300 via-sky-200 to-transparent text-teal-200 font-medium',
    glowColor: '#5eead4',
    negativeColor: '#f43f5e',
    invertedName: 'Heavy Stone',
    description: 'A gentle, high-altitude wind current swirling peacefully around you.',
    soundFreq: 380.00,
    relatedBiome: 'WINDY',
  },
  {
    id: 'rain_shower',
    name: 'Rain Shower droplets💧',
    chance: 120,
    color: 'from-blue-400 via-teal-300 to-sky-100 text-blue-300 font-bold',
    glowColor: '#60a5fa',
    negativeColor: '#ea580c',
    invertedName: 'Searing Ray',
    description: 'Condensation particles swirling in a localized vapor mist.',
    soundFreq: 390.00,
    relatedBiome: 'RAINY',
  },
  {
    id: 'decay_haze',
    name: 'Decay Haze☣️',
    chance: 150,
    color: 'from-[#581c87] via-[#a21caf] to-[#c084fc] text-fuchsia-400 font-bold',
    glowColor: '#a81caf',
    negativeColor: '#22c55e',
    invertedName: 'Primal Growth',
    description: 'A purple miasma that glitches the sensory field.',
    soundFreq: 180.00,
    relatedBiome: 'CORRUPTED',
  },
  {
    id: 'ruby_aura',
    name: 'Ruby Aura',
    chance: 150,
    color: 'from-rose-600 to-red-400 text-rose-500 font-bold',
    glowColor: '#f43f5e',
    negativeColor: '#14b8a6',
    invertedName: 'Cyan Core Shard',
    description: 'A crystallizing red plasma shroud humming with high value.',
    soundFreq: 392.00, // G4
  },
  {
    id: 'rainy_aura',
    name: 'Rainy Aura🌦️',
    chance: 250,
    color: 'from-blue-600 via-indigo-400 to-cyan-300 text-blue-400 font-black tracking-wide',
    glowColor: '#2563eb',
    negativeColor: '#eab308',
    invertedName: 'Drought Aura',
    description: '🌧️ RAINY EXCLUSIVE. An intense cloudburst that channels localized storm clouds.',
    soundFreq: 410.00,
    relatedBiome: 'RAINY',
  },
  {
    id: 'quartz',
    name: 'Quartz Sparkle',
    chance: 400,
    color: 'from-sky-300 to-indigo-200 text-sky-200 font-bold',
    glowColor: '#bae6fd',
    negativeColor: '#f97316',
    invertedName: 'Burnt Quartz',
    description: 'Crystalline rings reflecting deep cosmic rays.',
    soundFreq: 440.00, // A4
  },
  {
    id: 'lucky_aura',
    name: 'Lucky Aura ✨',
    chance: 500,
    color: 'from-yellow-300 via-yellow-400 to-amber-500 text-yellow-300 font-extrabold animate-pulse',
    glowColor: '#fbbf24',
    negativeColor: '#4f46e5',
    invertedName: 'Misfortune Shadow',
    description: 'A vibrantly gold aura that hums with incredible energy and emits high-frequency cosmic sparkles.',
    soundFreq: 1200.00, // High-pitched twinkle sound
  },
  {
    id: 'magma_eruption',
    name: 'Magma Eruption🌋',
    chance: 600,
    color: 'from-red-600 via-orange-600 to-yellow-500 text-red-500 font-extrabold animate-pulse',
    glowColor: '#dc2626',
    negativeColor: '#06b6d4',
    invertedName: 'Glacier Core',
    description: '🔥 FIRE EXCLUSIVE. Liquid heat pulsating to the rhythm of tectonic plates.',
    soundFreq: 460.00,
    relatedBiome: 'FIRE',
  },
  {
    id: 'gale_cyclone',
    name: 'Gale Cyclone🌪️',
    chance: 800,
    color: 'from-cyan-400 via-sky-300 to-zinc-400 text-sky-300 font-extrabold tracking-wide',
    glowColor: '#38bdf8',
    negativeColor: '#b45309',
    invertedName: 'Anchor Weight',
    description: '💨 WINDY EXCLUSIVE. High-velocity gale vortex tearing the fabric of space.',
    soundFreq: 480.00,
    relatedBiome: 'WINDY',
  },
  {
    id: 'jade',
    name: 'Jade Serpent',
    chance: 1000,
    color: 'from-emerald-500 via-teal-400 to-lime-200 text-emerald-400 font-bold',
    glowColor: '#34d399',
    negativeColor: '#ec4899',
    invertedName: 'Magenta Shroud',
    description: 'A serpentine wind of jade energy hovering gracefully.',
    soundFreq: 493.88, // B4
  },
  {
    id: 'glitch_matrix',
    name: 'Glitch Matrix👾',
    chance: 1200,
    color: 'from-[#3b0764] via-[#5c03cf] to-[#10b981] text-emerald-400 font-black tracking-wide font-mono',
    glowColor: '#7c3aed',
    negativeColor: '#f97316',
    invertedName: 'Organic Order',
    description: '⚠️ CORRUPTED EXCLUSIVE. Broken system registers bleeding through realities.',
    soundFreq: 220.00,
    relatedBiome: 'CORRUPTED',
  },
  {
    id: 'gold_star',
    name: 'Golden Orbit',
    chance: 2500,
    color: 'from-amber-400 via-yellow-500 to-orange-300 text-amber-300 font-extrabold',
    glowColor: '#fbbf24',
    negativeColor: '#3b82f6',
    invertedName: 'Cobalt Depth',
    description: 'A golden core of pure sunlight orbited by stellar bands.',
    soundFreq: 523.25, // C5
  },
  {
    id: 'solar_flare',
    name: 'Solar Flare☀️',
    chance: 5000,
    color: 'from-red-500 via-yellow-400 to-orange-600 text-yellow-300 font-black tracking-wider uppercase',
    glowColor: '#ea580c',
    negativeColor: '#0ea5e9',
    invertedName: 'Absolute Zero',
    description: '🔥 FIRE EXCLUSIVE. Extreme corona mass ejection radiating thermal vectors.',
    soundFreq: 550.00,
    relatedBiome: 'FIRE',
  },
  {
    id: 'eclipse',
    name: 'Solar Eclipse',
    chance: 8000,
    color: 'from-purple-800 via-black to-orange-500 text-orange-400 font-extrabold tracking-wider',
    glowColor: '#ea580c',
    negativeColor: '#0ea5e9',
    invertedName: 'Absolute Aurora',
    description: 'A pitch-black center haloed by extreme flaring orange arcs.',
    soundFreq: 587.33, // D5
  },
  {
    id: 'timeless_pulse',
    name: 'Timeless Pulse⌛',
    chance: 10000,
    color: 'from-indigo-600 via-pink-500 to-teal-300 text-pink-300 font-black tracking-widest uppercase',
    glowColor: '#ec4899',
    negativeColor: '#84cc16',
    invertedName: 'Mortality Decay',
    description: '🌌 ETERNITY EXCLUSIVE. Tick-tock. The perception of seconds disintegrates.',
    soundFreq: 600.00,
    relatedBiome: 'ETERNITY',
  },
  {
    id: 'typhoon_veil',
    name: 'Typhoon Veil🌀',
    chance: 12000,
    color: 'from-blue-900 via-indigo-700 to-sky-300 text-sky-200 font-black tracking-widest uppercase italic',
    glowColor: '#1d4ed8',
    negativeColor: '#b45309',
    invertedName: 'Desert Dust',
    description: '🌧️ RAINY EXCLUSIVE. Swirling vortex of pure elemental condensation.',
    soundFreq: 620.00,
    relatedBiome: 'RAINY',
  },
  {
    id: 'hurricane_grief',
    name: 'Hurricane Grief💨',
    chance: 15000,
    color: 'from-[#0f172a] via-[#1e293b] to-[#38bdf8] text-[#38bdf8] font-black tracking-widest uppercase italic',
    glowColor: '#0284c7',
    negativeColor: '#fda4af',
    invertedName: 'Feather Air',
    description: '💨 WINDY EXCLUSIVE. Searing cyclone air pressures compressing visual space.',
    soundFreq: 640.00,
    relatedBiome: 'WINDY',
  },
  {
    id: 'void_walker',
    name: 'Void Walker',
    chance: 18000,
    color: 'from-violet-950 via-purple-700 to-fuchsia-500 text-fuchsia-400 font-extrabold tracking-widest',
    glowColor: '#d946ef',
    negativeColor: '#84cc16',
    invertedName: 'Acid Sprout',
    description: 'Shifting spatial tears swirling with void static pulses.',
    soundFreq: 659.25, // E5
    relatedBiome: 'CORRUPTED',
  },
  {
    id: 'null_star',
    name: 'Null Inverted Star',
    chance: 25000, // Spawn: 1 in 25,000
    color: 'from-indigo-900 via-purple-900 to-blue-950 text-indigo-400 font-black tracking-widest uppercase',
    glowColor: '#3b82f6',
    negativeColor: '#eab308', // yellow/white core negation
    invertedName: 'Common Solar Beacon',
    description: '⚠️ NULL EXCLUSIVE. A deep neon blue core trailing pixelated black/purple star trails.',
    soundFreq: 739.99, // F#5
  },
  {
    id: 'singularity',
    name: 'Singularity',
    chance: 80000,
    color: 'from-black via-slate-900 to-violet-900 text-violet-400 font-black tracking-widest uppercase',
    glowColor: '#c084fc',
    negativeColor: '#22c55e',
    invertedName: 'Plentitude Core',
    description: 'A spatial anomaly bending gravity waves around a pixelated singularity.',
    soundFreq: 783.99, // G5
    relatedBiome: 'ETERNITY',
  },
  {
    id: 'paradox',
    name: 'Paradox Quantum',
    chance: 250000,
    color: 'from-pink-500 via-fuchsia-800 to-cyan-500 text-pink-300 font-black tracking-wider uppercase',
    glowColor: '#f472b6',
    negativeColor: '#10b981',
    invertedName: 'Causality Standard',
    description: 'A glowing vortex pulsing at contrasting wave lengths simultaneously.',
    soundFreq: 880.00, // A5
  },
  {
    id: 'eternity_core',
    name: 'Eternity Core🪐',
    chance: 250000,
    color: 'from-[#4c1d95] via-[#ec4899] to-[#818cf8] text-white font-black tracking-widest uppercase animate-bounce',
    glowColor: '#a855f7',
    negativeColor: '#581c87',
    invertedName: 'Transient Shard',
    description: '🌌 ETERNITY EXCLUSIVE. Pulsating dimensional stabilizer orb humming with chronological energy.',
    soundFreq: 900.00,
    relatedBiome: 'ETERNITY',
  },
  {
    id: 'nebula_cataclysm',
    name: 'Nebula Cataclysm',
    chance: 1000000,
    color: 'from-blue-600 via-purple-600 to-red-500 text-fuchsia-200 font-black tracking-widest uppercase',
    glowColor: '#e879f9',
    negativeColor: '#16a34a',
    invertedName: 'Static Dust Shroud',
    description: 'An entire gas cluster collapsing inside your atomic footprint.',
    soundFreq: 987.77, // B5
  },
  {
    id: 'infinite_genesis',
    name: 'Infinite Genesis🌌',
    chance: 3000000,
    color: 'from-[#312e81] via-[#818cf8] to-[#1e1b4b] text-indigo-200 font-black tracking-widest uppercase italic',
    glowColor: '#6366f1',
    negativeColor: '#ca8a04',
    invertedName: 'Desolate Ruin',
    description: '🌌 ETERNITY EXCLUSIVE. Stand at the cradle of expanding dimensional matrices.',
    soundFreq: 1050.00,
    relatedBiome: 'ETERNITY',
  },
  {
    id: 'twilight_god',
    name: 'Twilight Deity',
    chance: 5000000,
    color: 'from-amber-200 via-rose-500 to-indigo-900 text-amber-200 font-black tracking-widest uppercase animate-pulse',
    glowColor: '#fde047',
    negativeColor: '#2563eb',
    invertedName: 'Dawn Servant',
    description: 'Ascended stellar royalty. Dimensions warp to align with your roll.',
    soundFreq: 1109.73, // C#6
  },
  {
    id: 'celestial_reaper',
    name: 'Celestial Reaper',
    chance: 15000000,
    color: 'from-teal-400 via-emerald-600 to-purple-950 text-teal-300 font-black tracking-widest uppercase italic',
    glowColor: '#2dd4bf',
    negativeColor: '#f43f5e',
    invertedName: 'Mortal Shepard',
    description: 'Harvester of dying supernovas. Extremely rare and reality-bending.',
    soundFreq: 1318.51, // E6
  },
  {
    id: 'eternal_singularity',
    name: 'Eternal Infinity',
    chance: 40000000, // Gilded egg exclusive or 1 in 40M+
    color: 'from-amber-400 via-purple-600 to-cyan-400 text-white font-black tracking-widest uppercase italic animate-bounce',
    glowColor: '#38bdf8',
    negativeColor: '#e11d48',
    invertedName: 'Temporary Mortality',
    description: 'The final design of eternity. Absolute mastery over the Paradox RNG engine limits.',
    soundFreq: 1567.98, // G6
    relatedBiome: 'ETERNITY',
  }
];
